### ISSUE TITLE
Support multiarch Docker image builds

### ISSUE THREAD

**Issue by jdeanwallace** [tiny-pilot/janus-docker#3]
Port over [this CircleCI job](https://github.com/mtlynch/picoshare/pull/164/files) to automatically build our Janus Docker image for ARM and upload it Docker Hub.

**Comment by mtlynch** [comment]
Do we need more changes to the Docker image? My expectation was that we'd just use it for prototyping.

If we need more changes, I'd like to focus on [creating `.deb` packages for Janus instead](https://github.com/tiny-pilot/tinypilot-pro/issues/361). We should hopefully be able to use the same CircleCI example to do multiarch Debian package builds.

**Comment by jdeanwallace** [comment]
I added this issue on the back of [this PR review comment](https://github.com/tiny-pilot/janus-docker/pull/2#pullrequestreview-940851257). (weird that it didn't automatically link here 🤔 )

> If we need more changes, I'd like to focus on https://github.com/tiny-pilot/tinypilot-pro/issues/361.

Sounds good.
